"use client";
import { useEffect, useState } from "react";
import MobileFooter from "./components/MobileFooter";
import NavIcon from "./components/NavIcon";

const branches=[
 {id:"huaycan",name:"Huaycán — Ate",address:"Av. José Carlos Mariátegui Lote 06, Ate",phone:"51954664351",label:"+51 954 664 351"},
 {id:"chosica",name:"Chosica",address:"Av. Lima Sur, Lurigancho–Chosica",phone:"5116820778",label:"+51 1 682 0778"},
 {id:"amauta",name:"Amauta Las Américas",address:"Tienda para recojo",phone:"5116820778",label:"+51 1 682 0778"},
 {id:"puente",name:"Puente Nuevo",address:"Tienda para recojo",phone:"5116820778",label:"+51 1 682 0778"},
 {id:"riva",name:"Riva Agüero",address:"El Agustino · tienda para recojo",phone:"5116820778",label:"+51 1 682 0778"},
];
const favorites=[
 {name:"Chocolate clásico",desc:"Capas de chocolate y crema suave.",image:"/images/dominick-2.jpg",crop:"clean-a"},
 {name:"Mousse Dominick",desc:"Fresa, crema y acabado brillante.",image:"/images/dominick-4.jpg",crop:"clean-full"},
 {name:"Fresa & crema",desc:"Una combinación fresca y delicada.",image:"/images/dominick-3.jpg",crop:"clean-c"},
 {name:"Torta de chantilly",desc:"Ligera, cremosa y hecha a pedido.",image:"/images/dominick-3.jpg",crop:"clean-b"},
];
const moments=[
 {name:"Cumpleaños",image:"/images/dominick-2.jpg",crop:"clean-a"},
 {name:"Infantiles",image:"/images/dominick-1.jpg",crop:"clean-b"},
 {name:"Bodas",image:"/images/dominick-2.jpg",crop:"clean-b"},
 {name:"Elegantes",image:"/images/dominick-3.jpg",crop:"clean-b"},
];
function I({name}:{name:"pin"|"truck"|"cake"|"heart"|"check"|"whatsapp"|"instagram"|"arrow"|"menu"}){const p={pin:<><path d="M12 21s6-5 6-11a6 6 0 1 0-12 0c0 6 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></>,truck:<><path d="M3 7h11v10H3zM14 11h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,cake:<><path d="M4 10h16v10H4zM3 14c2 2 4-2 6 0s4-2 6 0 4-2 6 0M8 10V7M12 10V6M16 10V7"/></>,heart:<path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 0 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/>,check:<path d="m5 12 4 4L19 6"/>,whatsapp:<><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.4-4A8 8 0 1 1 20 11.5Z"/><path d="M9 8.5c1 3 2.7 4.7 5.7 5.5l1-1.2 1.6.8c-.3 1.2-1.5 2-2.7 1.8-3.8-.7-6.2-3.1-7-6.7-.2-1.2.7-2.5 1.8-2.8l.8 1.7L9 8.5Z"/></>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".7" fill="currentColor"/></>,arrow:<path d="M5 12h14m-6-6 6 6-6 6"/>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>};return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}

export default function Home(){const[branchId,setBranchId]=useState("huaycan");const[open,setOpen]=useState(false);const branch=branches.find(b=>b.id===branchId)??branches[0];useEffect(()=>{const s=localStorage.getItem("dominick-branch");if(s&&branches.some(b=>b.id===s))setBranchId(s)},[]);function choose(id:string){setBranchId(id);localStorage.setItem("dominick-branch",id)}const wa=`https://wa.me/${branch.phone}?text=${encodeURIComponent(`Hola Dominick, quisiera realizar un pedido en la sucursal ${branch.name}.`)}`;return <main className="home-page">
 <div className="home-top"><div className="home-container"><span><I name="pin"/> Lima, Perú</span><span><I name="truck"/> Entregas a domicilio</span><p>Hechas con amor, deliciosas por naturaleza</p><div className="home-top-actions"><a href="https://www.instagram.com/tortas_dominick/" target="_blank" rel="noreferrer" aria-label="Instagram de Dominick"><I name="instagram"/><span className="top-social-label">Instagram</span></a><a href="https://www.facebook.com/TortasyBuffetDominick/?ref=PROFILE_EDIT_xav_ig_profile_page_web#" target="_blank" rel="noreferrer" aria-label="Facebook de Dominick"><span className="facebook-mark" aria-hidden="true">f</span><span className="top-social-label">Facebook</span></a><a href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp de Dominick"><I name="whatsapp"/><span className="top-social-label">WhatsApp</span></a></div></div></div>
 <header className="home-header"><div className="home-container"><a className="home-logo" href="/"><b>Dominick</b><small>PASTELERÍA</small></a><nav className={open?"home-nav open":"home-nav"}>{[["Inicio","/"],["Tortas","/tortas"],["Postres","/postres"],["Diseños","/disenos"],["Arma tu torta","/arma-tu-torta"],["Nosotros","/nosotros"],["Contacto","/contacto"]].map(([label,href])=><a href={href} key={href}><NavIcon name={label}/><span>{label}</span></a>)}<div className="mobile-nav-social"><a href="https://www.instagram.com/tortas_dominick/" target="_blank" rel="noreferrer"><I name="instagram"/> Instagram</a><a href={wa} target="_blank" rel="noreferrer"><I name="whatsapp"/> WhatsApp</a></div></nav><a className="home-quote" href="/arma-tu-torta"><I name="cake"/> Arma tu torta</a><button className="home-menu" onClick={()=>setOpen(!open)} aria-label="Abrir menú"><I name="menu"/></button></div></header>
 <section className="home-hero"><div className="home-container"><div className="home-hero-copy"><p>HECHAS PARA</p><h1><span>Momentos que</span><span>se quedan <em>contigo</em></span></h1><span>Tortas y postres personalizados con ingredientes seleccionados y mucho amor.</span><div><a className="home-btn solid" href="/tortas">Ver tortas <I name="arrow"/></a><a className="home-btn outline" href="/arma-tu-torta">Arma tu torta</a></div></div><div className="home-hero-image"><img src="/images/dominick-hero-frutas.webp" alt="Torta elegante de crema y frutas"/></div></div></section>
 <section className="home-benefits"><div className="home-container"><article><I name="cake"/><div><b>100% personalizado</b><span>Diseñamos tu torta ideal</span></div></article><article><I name="heart"/><div><b>Ingredientes de calidad</b><span>Seleccionados con cariño</span></div></article><article><I name="check"/><div><b>Hecho a pedido</b><span>Fresco especialmente para ti</span></div></article><article><I name="truck"/><div><b>Entrega segura</b><span>Cuidamos cada detalle</span></div></article></div></section>
 <section className="home-section"><div className="home-container"><div className="home-heading"><div><p>NUESTRAS FAVORITAS</p><h2>Cuatro tortas para enamorarte</h2></div><a href="/tortas">Ver todo el catálogo <I name="arrow"/></a></div><div className="home-products">{favorites.map(p=><article key={p.name}><div className={`home-card-image ${p.crop}`}><img src={p.image} alt={p.name}/></div><h3>{p.name}</h3><p>{p.desc}</p><a href={wa} target="_blank" rel="noreferrer">Ver / Cotizar <I name="arrow"/></a></article>)}</div></div></section>
 <section className="home-section home-moments"><div className="home-container"><div className="home-heading"><div><p>PARA CELEBRAR</p><h2>Encuentra la torta para tu momento</h2></div></div><div className="home-categories">{moments.map(m=><a href="/disenos" key={m.name}><div className={`home-category-image ${m.crop}`}><img src={m.image} alt={m.name}/></div><span>{m.name}</span><I name="arrow"/></a>)}</div></div></section>
 <section className="home-custom"><div className="home-container"><div><p>HECHA COMO LA IMAGINAS</p><h2>¿Tienes una idea especial?</h2><span>Elige tamaño, sabor, relleno y acabado en nuestro configurador.</span><a className="home-btn solid" href="/arma-tu-torta">Arma tu torta <I name="arrow"/></a></div><div className="home-custom-image clean-full"><img src="/images/dominick-4.jpg" alt="Torta personalizada Dominick"/></div></div></section>
 <MobileFooter branch={branch.name} whatsapp={wa}/>
 <footer className="home-footer"><div className="home-container home-footer-grid"><div className="footer-brand"><a className="home-logo light" href="/"><b>Dominick</b><small>PASTELERÍA</small></a><p>Hechas con amor, creadas para quedarse en tu memoria.</p></div><div><b>Navegación</b><a href="/">Inicio</a><a href="/tortas">Tortas</a><a href="/postres">Postres</a><a href="/disenos">Diseños</a></div><div><b>Información</b><a href="/nosotros">Nuestra historia</a><a href="/contacto">Sucursales</a><a href="/arma-tu-torta">Arma tu torta</a><a href="/contacto">Preguntas frecuentes</a></div><div><b>Políticas</b><a href="/contacto">Entregas y recojo</a><a href="/contacto">Formas de pago</a><a href="/contacto">Cambios y cancelaciones</a><a href="/contacto">Privacidad</a></div><div><b>Contacto</b><span>{branch.name}</span><a href="https://www.instagram.com/tortas_dominick/" target="_blank" rel="noreferrer">@tortas_dominick</a><a href="https://www.facebook.com/TortasyBuffetDominick/?ref=PROFILE_EDIT_xav_ig_profile_page_web#" target="_blank" rel="noreferrer">Facebook Dominick</a><div className="home-social"><a href="https://www.instagram.com/tortas_dominick/" target="_blank" rel="noreferrer" aria-label="Instagram"><I name="instagram"/></a><a href="https://www.facebook.com/TortasyBuffetDominick/?ref=PROFILE_EDIT_xav_ig_profile_page_web#" target="_blank" rel="noreferrer" aria-label="Facebook"><span className="facebook-mark" aria-hidden="true">f</span></a><a href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp"><I name="whatsapp"/></a></div></div><small>© 2026 Tortas Dominick · Lima, Perú · Todos los derechos reservados.</small></div></footer>
 <a className="home-wa" href={wa} target="_blank" rel="noreferrer" aria-label="Pedir por WhatsApp"><I name="whatsapp"/></a>
 </main>}
